// Programa   : SETFIELDEFAULTALL
// Fecha/Hora : 03/02/2024 06:10:07
// Propósito  : Definicion para todas las Tablas
// Creado Por :
// Llamado por:
// Aplicación :
// Tabla      :

#INCLUDE "DPXBASE.CH"

PROCE MAIN()

  IF oDp:cType="SGE"

    EJECUTAR("SETFIELDEFAULT","DPCTAEGRESO","CEG_CODCLA",[&oDp:cCtaIndef])
    EJECUTAR("SETFIELDEFAULT","DPPROVEEDOR","PRO_ZONANL",["N"])
    EJECUTAR("SETFIELDEFAULT","DPPROVEEDOR","PRO_PAIS"  ,[&oDp:cPais])
    EJECUTAR("SETFIELDEFAULT","DPPROVEEDOR","PRO_ESTADO",[&oDp:cEstado])
    EJECUTAR("SETFIELDEFAULT","DPPROVEEDOR","PRO_MUNICI",[&oDp:cMunicipio])
    EJECUTAR("SETFIELDEFAULT","DPPROVEEDOR","PRO_PARROQ",[&oDp:cParroquia])

    EJECUTAR("SETFIELDEFAULT","DPPROVEEDOR","PRO_ACTIVI",[&oDp:cActividad])
    EJECUTAR("SETFIELDEFAULT","DPPROVEEDOR","PRO_CODCLA",[&oDp:cProClasifica])
    EJECUTAR("SETFIELDEFAULT","DPPROVEEDOR","PRO_CODRMU",[&oDp:cCodRmu])

    EJECUTAR("SETFIELDEFAULT","DPCLIENTES"      ,"CLI_ZONANL",["N"])
    EJECUTAR("SETFIELDEFAULT","DPPROVEEDORPROG" ,"PGC_CTAEGR",[&oDp:cCtaIndef])
    EJECUTAR("SETFIELDEFAULT","DPCTAEGRESO"     ,"CEG_CODCLA",[&oDp:cCtaIndef])

  ENDIF

RETURN .T.
// EOF


